# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EKYC_Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EKYC_Sample
	pod 'RadioGroup'
  
  #FEKYC dependencies
  pod 'MBProgressHUD'
  pod 'Alamofire', '~> 4.7.2'
  pod 'TPKeyboardAvoiding'
  pod 'HydraAsync'
  pod 'IDMPhotoBrowser'
end
